### ISSUE TITLE
Fox Sightings issue in pattern C→

### ISSUE THREAD

**Issue by hikarievo** [Sturalke/FauxHollowsProbabilisticSolver#4]
Strategy: any
Fox Sightings: checked

Issue: 
After blocked all 5 blocks in pattern C→,  only the top 2 blocks are retained, the left 3 blocks changing to the foxes as well as other possible foxes.

**Comment by Shinx02** [comment]
have had the same issue with C↓
Following some screen shots: https://imgur.com/a/IKj3VSY

**Comment by Sturalke** [comment]
Turns out when creating the templates for matching patterns, I accidentally switched the matching patterns for C→ and C↓. I've now checked all 16 patterns to make sure they match their corresponding data.
