### ISSUE TITLE
Sightings error in Pattern D↑

### ISSUE THREAD

**Issue by hikarievo** [Sturalke/FauxHollowsProbabilisticSolver#8]
![QQ截图20230813134520](https://github.com/Sturalke/FauxHollowsProbabilisticSolver/assets/8074722/2d481c51-55bc-41b3-96e2-049a1c9975b4)
The 3rd one from last row in Pattern D↑, show as attached

**Comment by Sturalke** [comment]
Finally fixed now, likely due to out of date data. Issue is now resolved by commit ca7ec11.
